mdp_mssql_mine:
  target: dev
  outputs:
    dev:
      type: snowflake
      #account:"{{ env_var('SNOWFLAKE_ACCOUNT', 'webhdwh-rj60778') }}"
      account:  "dg63583.eu-west-1" #
      user: "{{ env_var('SNOWFLAKE_USER', 'neemba_user') }}"
      password: "Neemb@Password2025" #"{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'TRANSFORM') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'COMPUTE_WH') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'NEEMBA') }}"
      schema: mines
      threads: 2
